title: Hi! I'm Kevin Lee
logo: assets/portfolio_portrait_circle.png
text: Embedded SW/SYS engineer and enthusiast
show_downloads: false
remote_theme: pages-themes/slate@v0.2.0
header_pages:
  - index.md
  - resume.md
  - proj_vcu_ems.md
  - proj_p5v04a_camera.md

plugins:
  - jekyll-remote-theme

# Include custom stylesheet
include:
  - assets/css/custom.css